version: 2

defaults: &defaults
  working_directory: ~/repo

jobs:
  build:
    <<: *defaults

    docker:
      - image: crichmond1989/svn:node-8-slim

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run lint

      - run: npm run build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - LICENSE
            - package.json
            - README.md
            - dist

      - store_artifacts:
          path: LICENSE

      - store_artifacts:
          path: package.json

      - store_artifacts:
          path: README.md

      - store_artifacts:
          path: dist

      - run: npm run cover

      - store_test_results:
          path: test-results

  deploy:
    <<: *defaults

    docker:
      - image: node:8-slim

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master